<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateReservationRoomTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('reservation_room', function (Blueprint $table) {
            $table->increments('reservation_room_id');
            $table->integer('reservation_id');
            $table->integer('room_id');
            $table->integer('room_seq')->nullable();
            $table->string('reservation_customer_name', 50)->nullable();
            $table->tinyInteger('reservation_guest');
            $table->string('reservation_tel', 10);
            $table->tinyInteger('reservation_status')->nullable()->comment('1 : Pay , 0:  Not pay');
            $table->integer('reservation_cost')->nullable();
            $table->string('reservation_agency', 50)->nullable();
            $table->date('reservation_lastdate')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('reservation_room');
    }
}
